[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FOURTHWALL_SHOP_URL,VITE_FOURTHWALL_STOREFRONT_TOKEN,VITE_DISCORD_CLIENT_ID,VITE_DISCORD_GUILD_ID,VITE_IMGBB_API_KEY"